spring.application.name=foro

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/foro_hub
spring.datasource.username=postgres
spring.datasource.password=Luismario23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.secret=mi_secreto_super_seguro_123